# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  mobanfile:  # id of input
    description: 'Who to greet'
    required: true
    default: '.moban.yml'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mobanfile }}

